# Lab 7: Interactive Dashboard with Plotly Dash

The runnable app is `dashboard/app.py`. It implements the launch-site dropdown, success pie chart, payload range slider, and outcome scatter plot, plus summaries for the five visual-analysis questions.

In [1]:
from pathlib import Path
import sys

candidates = [Path.cwd(), *Path.cwd().parents, Path.cwd() / 'spacex-capstone']
PROJECT_DIR = next(path for path in candidates if (path / 'dashboard' / 'app.py').is_file())
sys.path.insert(0, str(PROJECT_DIR / 'dashboard'))
import app as spacex_dashboard

client = spacex_dashboard.app.server.test_client()
assert client.get('/').status_code == 200
print('Dash page status:', client.get('/').status_code)
print('Dropdown sites:', spacex_dashboard.site_names)
print('Payload slider:', spacex_dashboard.payload_min, 'to', spacex_dashboard.payload_max, 'kg')
for question, result in spacex_dashboard.dashboard_insights().items():
    print(f'--- {question} ---')
    display(result.round(3))

Dash page status: 200
Dropdown sites: ['CCAFS SLC 40', 'KSC LC 39A', 'VAFB SLC 4E']
Payload slider: 0 to 16000 kg
--- site_success_counts ---

              launches  successful  success_rate
LaunchSite
CCAFS SLC 40        55          33         0.600
KSC LC 39A          22          17         0.773
VAFB SLC 4E         13          10         0.769

--- site_success_rates ---

              launches  successful  success_rate
LaunchSite
KSC LC 39A          22          17         0.773
VAFB SLC 4E         13          10         0.769
CCAFS SLC 40        55          33         0.600

--- payload_success_rates ---

                launches  success_rate
PayloadRange
[12000, 13000)         1         1.000
[13000, 14000)         1         1.000
[7000, 8000)           2         1.000
[9000, 10000)          8         0.875
[15000, 16000)        13         0.846
[1000, 2000)           5         0.800
[3000, 4000)          10         0.800
[2000, 3000)          16         0.625
[4000, 5000)           9         0.556
[5000, 6000)           8         0.500
[0, 1000)              7         0.429
[6000, 7000)          10         0.400

--- booster_success_rates ---

                        launches  success_rate
BoosterVersionCategory
v1.1                           6         1.000
Block 5                       39         0.846
Full Thrust                   15         0.733
Block 4                       11         0.545
v1.0                          19         0.211

## Run the application

From the project root, run `python dashboard/app.py` and open `http://127.0.0.1:8050`. Booster categories are derived from the supplied `Block` column because the source dataset labels the booster version only as `Falcon 9`.